// let btn1 = document.querySelector("#btn1");

// btn1.onclick = (evt) => {
//     console.log(evt);
//     console.log(evt.type);
//     console.log(evt.target);
//     console.log(evt.clientX, evt.clientY);
    // let a = 26;
    // console.log(a);
// }

// btn1.onclick = () => {
//     console.log("HANDLER2");
// }

// let div = document.querySelector("div");
// div.onmouseover = () => {
//     console.log("you are inside div");
// };

// btn1.addEventListener("cllck", (evt) => {
//     console.log("Button1 was clicked");
//     console.log(evt);
//     console.log(evt.type);
// });  not worked

// btn1.addEventListener("cllck", () => {
//     console.log("Button1 was clicked - handler2");
// });  not worked

// pratice event Q

// let modeBtn = document.querySelector("#mode");
// let body = document.querySelector("body"); // css type
// let currMode = "light";

// modeBtn.addEventListener("click", () => {
//     if (currMode === "light") {
//         currMode = "dark";
//         body.classList.add("dark"); // css type
//         body.classList.remove("light"); // css type
//         // document.querySelector("body").style.backgroundColor = "black"; || js type
//     } else {
//         currMode = "light";
//         body.classList.add("light"); // css type
//          body.classList.remove("dark"); // css type
//         // document.querySelector("body").style.backgroundColor = "white"; || js type
//     }

//     console.log(currMode);
// });




